### ISSUE TITLE
DOIs for datasets in eNanoMapper databases, BioStudies and other standard data repositories

### ISSUE THREAD

**Issue by thomasexner** [BiGCAT-UM/ELIXIR-Tox#13]
Investigate ways how to use approaches from ELIXIR or OpenAIRE/Zenodo for assigning DOIs to specific datasets in these databases, which would make them more accessible and can be used to reference the datasets in publications.

**Comment by egonw** [comment]
Set up at https://nanocommons.github.io/datasets/
