### ISSUE TITLE
Create Turtle file of AOP Wiki XML

### ISSUE THREAD

**Issue by marvinm2** [BiGCAT-UM/ELIXIR-Tox#24]
The initial step towards a semantic integration of AOP Wiki (https://aopwiki.org/downloads), eventually allowing SPARQL queries on the contents of this database.

**Comment by egonw** [comment]
My recommendations:

- [ ] create a GitHub repo for the code that does the transformation
- [ ] set up a Jenkins job based on this repo that 1. downloads the AOPWiki data, 2. runs the code from the repo to create Turtle
- [ ] define a number of tests that make sure the Turtle is reasonable

Check the license of AOPWiki... it's Open, right? If not, delete the turtle from the Jenkins job workspace.

**Comment by egonw** [comment]
ping @marvinm2, can you update this issue report with the current status, progress, pointers?

**Comment by marvinm2** [comment]
A script is created for ttl generation, which is valid Turtle. SPARQL queries can be done, and it is presented in a poster at SWAT4HCLS: https://doi.org/10.6084/m9.figshare.7735067.v1

However, some elements are missing/lacking annotations, and we plan to add more elements to the RDF, such as metabolite identifiers for stressors and links to data sets for KEs (ToxCast)

**Comment by egonw** [comment]
The paper is being written up.
