### ISSUE TITLE
reboot/boost of the process

### ISSUE THREAD

**Issue by egonw** [BiGCAT-UM/ELIXIR-Tox#27]
Short term actions:

1. update co-applicants: https://github.com/egonw/ELIXIR-Tox/issues/21
2. contact all HoNs: https://github.com/egonw/ELIXIR-Tox/issues/22
3. formlize the leader team: https://github.com/egonw/ELIXIR-Tox/issues/19

**Comment by Chris-Evelo** [comment]
What is the plan Egon?

**Comment by egonw** [comment]
The above three steps... but please complement.

**Comment by egonw** [comment]
yes, that list is in this repo (can still grow, of course): https://github.com/egonw/ELIXIR-Tox/blob/master/participants.tsv

**Comment by Chris-Evelo** [comment]
OK, have all these people been contacted? Do we have an email list? 

It is important to figure out whether they are really connected to the nodes for their countries.

All Dutch universities and research institutes are.

**Comment by egonw** [comment]
Hi all, a quick update. It's clear that with all the current work I have now, I don't have enough I cannot lead this. I will want to be active in the community, but I cannot practically lead it. We're internally discussion whom can do the practical work. This person does not have be someone from the leadership team, but we basically need a project manager, which could be a postdoc, whom has enough time to get the relevant people together enough, set up meetings, work out meeting notes, that sort of stuff. Of course, this person can combine this with actually be a face for this community.

**Comment by RobStierum** [comment]
Hoi Egon,

Ik zit een beetje in het zelfde schuitje en ook bij mij radiostilte. Sorry hiervoor zeker niet uit desinteresse

Binnen TNO heb ik weinig ruimte (zowel qua tijd als budget. En we hebben net een exposome project gehonoreerd gekregen(EPHOR, occupational exposome) waar we nu voor aan de bak moeten (contractonderhandelingen etc.) om te starten volgend jaar

Hoe zat het nu met het oorspronkelijke idee a.d.h.v. de white paper, kwam er/was er nu vanuit elixer al goedkeuring voor een tox example case project?
Ik heb wat stagiares misschien binnenkort biedt dat soelaas, maar misschien te junior?

Zoals je denk ik van Chris wel weet zijn we bezig met het virtual human inititative (NWA) for safety van Juliette legler, misschien kan dat complementair/als use case dienen voor de elixer tox community?

Groeten ,
Rob

**Comment by Chris-Evelo** [comment]
Wat betreft:

Hoe zat het nu met het oorspronkelijke idee a.d.h.v. de white paper, kwam er/was er nu vanuit elixer al goedkeuring voor een tox example case project?

Nee, niet op het niveau dat we toestemming hebben om een whitepaper te schrijven. Wel dat we het een volgende HON in een uitgebreidere versie kunnen presenteren, waarbij de HoN vooral meer inbreng van diverse nodes willen zien. Er is een beetje een informele bereidheid om ons tussen twee officiele rondes (waarbij de volgende een paar jaar weg is) in te moffelen. Helemaal officieel waren we ooit te laat. We moeten dat natuurlijk wel juist met wat enthusiasme oppakken en daar zit dus een probleem.

Koppeling met NWA is inhoudelijk een goed idee (en andersom ook trouwens het kan NWA versterken om een gode link met ELIXIR te hebben). Maar het is natuurlijk wel alleen NL en lost dus het probleem van node diversiteit niet op.

   Groeten, Chris
